---
name: Browser Extension CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y zip
          zip -rm letterboxd-companion.zip src

      - name: Upload release artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./letterboxd-companion.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
