name: Browser Extension CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier:
    name: Prettier Formatting Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Prettify code
        uses: creyD/prettier_action@v4
        with:
          prettier_options: --write **/*.{html,js} --config .prettierrc.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linter:
    name: Lint Code Base
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          DEFAULT_BRANCH: main
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
